/**********************************************************************

	--- Qt Architect generated file ---

	File: kscolourpickerData.cpp
	Last generated: Tue Jul 28 14:21:49 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "kscolourpickerData.h"

#define Inherited QDialog


kscolourpickerData::kscolourpickerData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	PB_Pick = new("QPushButton") QPushButton( this, "PushButton_33" );
	PB_Pick->setGeometry( 120, 50, 100, 25 );
	PB_Pick->setMinimumSize( 10, 10 );
	PB_Pick->setMaximumSize( 32767, 32767 );
	PB_Pick->setText( i18n("Pick") );
	PB_Pick->setAutoRepeat( FALSE );
	PB_Pick->setAutoResize( FALSE );

	PB_Cancel = new("QPushButton") QPushButton( this, "PushButton_34" );
	PB_Cancel->setGeometry( 235, 50, 100, 25 );
	PB_Cancel->setMinimumSize( 10, 10 );
	PB_Cancel->setMaximumSize( 32767, 32767 );
	PB_Cancel->setText( i18n("Cancel") );
	PB_Cancel->setAutoRepeat( FALSE );
	PB_Cancel->setAutoResize( FALSE );

	SLE_SampleText = new("QLineEdit") QLineEdit( this, "LineEdit_1" );
	SLE_SampleText->setGeometry( 15, 50, 95, 25 );
	SLE_SampleText->setMinimumSize( 10, 10 );
	SLE_SampleText->setMaximumSize( 32767, 32767 );
	SLE_SampleText->setText( i18n("Sample Colour") );
	SLE_SampleText->setMaxLength( 32767 );
	SLE_SampleText->setEchoMode( QLineEdit::Normal );
	SLE_SampleText->setFrame( TRUE );

	resize( 350,80 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


kscolourpickerData::~kscolourpickerData()
{
}
