/**********************************************************************

	--- Qt Architect generated file ---

	File: KSCutDialogData.h
	Last generated: Sun Feb 1 13:35:25 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef KSCutDialogData_included
#define KSCutDialogData_included

#include <qdialog.h>
#include "cutmle.h"
#include <kapp.h>

class KSCutDialogData : public QDialog
{
    Q_OBJECT

public:

    KSCutDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~KSCutDialogData();

public slots:


protected slots:

    virtual void terminate();
    virtual void copy();

protected:
    KCutMLE* IrcMLE;

};

#endif // KSCutDialogData_included
