/**********************************************************************

	--- Qt Architect generated file ---

	File: KSCutDialogData.cpp
	Last generated: Sun Feb 1 13:35:25 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "KSCutDialogData.h"

#define Inherited QDialog

#include <qpushbt.h>
#include <qlayout.h>

KSCutDialogData::KSCutDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	IrcMLE = new("KCutMLE") KCutMLE( this, "User_1" );
	IrcMLE->setGeometry( 5, 5, 580, 320 );
	IrcMLE->setMinimumSize( 10, 320 );
	IrcMLE->setMaximumSize( 32767, 320 );

	QPushButton* dlgedit_PushButton_9;
	dlgedit_PushButton_9 = new("QPushButton") QPushButton( this, "PushButton_9" );
	dlgedit_PushButton_9->setGeometry( 370, 5, 100, 30 );
	dlgedit_PushButton_9->setMinimumSize( 100, 30 );
	dlgedit_PushButton_9->setMaximumSize( 100, 30 );
	connect( dlgedit_PushButton_9, SIGNAL(clicked()), SLOT(copy()) );
	dlgedit_PushButton_9->setText( i18n("Cop&y") );
	dlgedit_PushButton_9->setAutoRepeat( FALSE );
	dlgedit_PushButton_9->setAutoResize( FALSE );

	QPushButton* dlgedit_PushButton_10;
	dlgedit_PushButton_10 = new("QPushButton") QPushButton( this, "PushButton_10" );
	dlgedit_PushButton_10->setGeometry( 475, 5, 100, 30 );
	dlgedit_PushButton_10->setMinimumSize( 100, 30 );
	dlgedit_PushButton_10->setMaximumSize( 100, 30 );
	connect( dlgedit_PushButton_10, SIGNAL(clicked()), SLOT(terminate()) );
	dlgedit_PushButton_10->setText( i18n("&Close") );
	dlgedit_PushButton_10->setAutoRepeat( FALSE );
	dlgedit_PushButton_10->setAutoResize( FALSE );

	QBoxLayout* dlgedit_layout_1 = new("QBoxLayout") QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	dlgedit_layout_1->addStrut( 0 );
	dlgedit_layout_1->addWidget( IrcMLE, 1, 9 );
	QBoxLayout* dlgedit_layout_1_2 = new("QBoxLayout") QBoxLayout( QBoxLayout::LeftToRight, 5, NULL );
	dlgedit_layout_1->addLayout( dlgedit_layout_1_2, 0 );
	dlgedit_layout_1_2->addStrut( 0 );
	dlgedit_layout_1_2->addStretch( 1 );
	dlgedit_layout_1_2->addWidget( dlgedit_PushButton_9, 0, 36 );
	dlgedit_layout_1_2->addWidget( dlgedit_PushButton_10, 0, 36 );


	resize( 590,370 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


KSCutDialogData::~KSCutDialogData()
{
}
void KSCutDialogData::copy()
{
}
void KSCutDialogData::terminate()
{
}

#include "KSCutDialogData.moc"
