/**********************************************************************

	--- Qt Architect generated file ---

	File: speeddialogData.h
	Last generated: Sun Dec 21 09:13:46 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef speeddialogData_included
#define speeddialogData_included

#include <qdialog.h>
#include <qslider.h>
#include <qlcdnum.h>
#include <kapp.h>

class speeddialogData : public QDialog
{
    Q_OBJECT

public:

    speeddialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~speeddialogData();

public slots:


protected slots:

    virtual void terminate();
    virtual void updateTick(int);
    virtual void updateStep(int);

protected:
    QSlider* sliderTick;
    QSlider* sliderStep;
    QLCDNumber* lcdTick;
    QLCDNumber* lcdStep;

};

#endif // speeddialogData_included
