/**********************************************************************

	--- Qt Architect generated file ---

	File: UserMenuRefData.h
	Last generated: Mon Jan 19 21:30:48 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef UserMenuRefData_included
#define UserMenuRefData_included

#include <qframe.h>
#include <qchkbox.h>
#include <qpushbt.h>
#include <qlistbox.h>
#include <qlined.h>
#include <qcombo.h>
#include <kapp.h>

class UserMenuRefData : public QFrame
{
    Q_OBJECT

public:

    UserMenuRefData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~UserMenuRefData();

public slots:

    virtual void terminate();

protected slots:

    virtual void insertMenu();
    virtual void typeSetActive(int);
    virtual void deleteMenu();
    virtual void newHighlight(int);
    virtual void modifyMenu();

protected:
    QLineEdit* MenuName;
    QLineEdit* MenuCommand;
    QComboBox* MenuType;
    QCheckBox* MenuOpOnly;
    QPushButton* ApplyButton;
    QPushButton* insertButton;
    QListBox* MainListBox;

};

#endif // UserMenuRefData_included
