/**********************************************************************

	--- Qt Architect generated file ---

	File: editGroupData.h
	Last generated: Mon Oct 5 09:48:30 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef editGroupData_included
#define editGroupData_included

#include <qdialog.h>
#include <qpushbt.h>
#include <qlistbox.h>

class editGroupData : public QDialog
{
    Q_OBJECT

public:

    editGroupData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~editGroupData();

public slots:


protected slots:

    virtual void del();
    virtual void add();
    virtual void ok();
    virtual void cancel();

protected:
    QListBox* m_Users;
    QListBox* m_Group;
    QPushButton* pbok;
    QPushButton* pbcancel;
    QPushButton* pbadd;
    QPushButton* pbdel;

};

#endif // editGroupData_included
