/**********************************************************************

	--- Qt Architect generated file ---

	File: editGroupData.cpp
	Last generated: Mon Oct 5 09:48:30 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>

#include "misc.h"

#include "editGroupData.h"

#define Inherited QDialog

#include <qlabel.h>

editGroupData::editGroupData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 20480 )
{
	QLabel* qtarch_Label_4;
	qtarch_Label_4 = new QLabel( this, "Label_4" );
	qtarch_Label_4->setGeometry( 5, 5, 200, 30 );
	qtarch_Label_4->setMinimumSize( 200, 30 );
	qtarch_Label_4->setMaximumSize( 200, 30 );
	qtarch_Label_4->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_4->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_4->setText( i18n("Users not in Group") );
	qtarch_Label_4->setAlignment( 289 );
	qtarch_Label_4->setMargin( -1 );
	qtarch_Label_4->setAutoResize(true);

	QLabel* qtarch_Label_5;
	qtarch_Label_5 = new QLabel( this, "Label_5" );
	qtarch_Label_5->setGeometry( 275, 5, 200, 30 );
	qtarch_Label_5->setMinimumSize( 200, 30 );
	qtarch_Label_5->setMaximumSize( 200, 30 );
	qtarch_Label_5->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_5->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_5->setText( i18n("Users in Group") );
	qtarch_Label_5->setAlignment( 289 );
	qtarch_Label_5->setMargin( -1 );
	qtarch_Label_5->setAutoResize(true);

	m_Users = new QListBox( this, "m_Users" );
	m_Users->setGeometry( 5, 40, 210, 150 );
	m_Users->setMinimumSize( 0, 0 );
	m_Users->setMaximumSize( 32767, 32767 );
	m_Users->setFocusPolicy( QWidget::StrongFocus );
	m_Users->setBackgroundMode( QWidget::PaletteBase );
	m_Users->setFontPropagation( QWidget::SameFont );
	m_Users->setPalettePropagation( QWidget::SameFont );
	m_Users->setFrameStyle( 51 );
	m_Users->setLineWidth( 2 );
	m_Users->setMultiSelection( FALSE );

	m_Group = new QListBox( this, "m_Group" );
	m_Group->setGeometry( 275, 40, 210, 150 );
	m_Group->setMinimumSize( 0, 0 );
	m_Group->setMaximumSize( 32767, 32767 );
	m_Group->setFocusPolicy( QWidget::StrongFocus );
	m_Group->setBackgroundMode( QWidget::PaletteBase );
	m_Group->setFontPropagation( QWidget::SameFont );
	m_Group->setPalettePropagation( QWidget::SameFont );
	m_Group->setFrameStyle( 51 );
	m_Group->setLineWidth( 2 );
	m_Group->setMultiSelection( FALSE );

	pbok = new QPushButton( this, "pbok" );
	pbok->setGeometry( 140, 195, 100, 30 );
	pbok->setMinimumSize( 100, 30 );
	pbok->setMaximumSize( 100, 30 );
	connect( pbok, SIGNAL(clicked()), SLOT(ok()) );
	pbok->setFocusPolicy( QWidget::TabFocus );
	pbok->setBackgroundMode( QWidget::PaletteBackground );
	pbok->setFontPropagation( QWidget::NoChildren );
	pbok->setPalettePropagation( QWidget::NoChildren );
	pbok->setText( i18n("OK") );
	pbok->setAutoRepeat( FALSE );
	pbok->setAutoResize( FALSE );

	pbcancel = new QPushButton( this, "pbcancel" );
	pbcancel->setGeometry( 250, 195, 100, 30 );
	pbcancel->setMinimumSize( 100, 30 );
	pbcancel->setMaximumSize( 100, 30 );
	connect( pbcancel, SIGNAL(clicked()), SLOT(cancel()) );
	pbcancel->setFocusPolicy( QWidget::TabFocus );
	pbcancel->setBackgroundMode( QWidget::PaletteBackground );
	pbcancel->setFontPropagation( QWidget::NoChildren );
	pbcancel->setPalettePropagation( QWidget::NoChildren );
	pbcancel->setText( i18n("Cancel") );
	pbcancel->setAutoRepeat( FALSE );
	pbcancel->setAutoResize( FALSE );

	QLabel* qtarch_Label_6;
	qtarch_Label_6 = new QLabel( this, "Label_6" );
	qtarch_Label_6->setGeometry( 5, 195, 125, 30 );
	qtarch_Label_6->setMinimumSize( 0, 0 );
	qtarch_Label_6->setMaximumSize( 32767, 32767 );
	qtarch_Label_6->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_6->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_6->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_6->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_6->setText( "" );
	qtarch_Label_6->setAlignment( 289 );
	qtarch_Label_6->setMargin( -1 );

	QLabel* qtarch_Label_7;
	qtarch_Label_7 = new QLabel( this, "Label_7" );
	qtarch_Label_7->setGeometry( 360, 195, 125, 30 );
	qtarch_Label_7->setMinimumSize( 0, 0 );
	qtarch_Label_7->setMaximumSize( 32767, 32767 );
	qtarch_Label_7->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_7->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_7->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_7->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_7->setText( "" );
	qtarch_Label_7->setAlignment( 289 );
	qtarch_Label_7->setMargin( -1 );

	pbadd = new QPushButton( this, "pbadd" );
	pbadd->setGeometry( 225, 83, 40, 30 );
	pbadd->setMinimumSize( 40, 30 );
	pbadd->setMaximumSize( 40, 30 );
	connect( pbadd, SIGNAL(clicked()), SLOT(add()) );
	pbadd->setFocusPolicy( QWidget::TabFocus );
	pbadd->setBackgroundMode( QWidget::PaletteBackground );
	pbadd->setFontPropagation( QWidget::NoChildren );
	pbadd->setPalettePropagation( QWidget::NoChildren );
	pbadd->setText( "->" );
	pbadd->setAutoRepeat( FALSE );
	pbadd->setAutoResize( FALSE );

	pbdel = new QPushButton( this, "pbdel" );
	pbdel->setGeometry( 225, 118, 40, 30 );
	pbdel->setMinimumSize( 40, 30 );
	pbdel->setMaximumSize( 40, 30 );
	connect( pbdel, SIGNAL(clicked()), SLOT(del()) );
	pbdel->setFocusPolicy( QWidget::TabFocus );
	pbdel->setBackgroundMode( QWidget::PaletteBackground );
	pbdel->setFontPropagation( QWidget::NoChildren );
	pbdel->setPalettePropagation( QWidget::NoChildren );
	pbdel->setText( "<-" );
	pbdel->setAutoRepeat( FALSE );
	pbdel->setAutoResize( FALSE );

	QLabel* qtarch_Label_8;
	qtarch_Label_8 = new QLabel( this, "Label_8" );
	qtarch_Label_8->setGeometry( 225, 40, 40, 38 );
	qtarch_Label_8->setMinimumSize( 0, 0 );
	qtarch_Label_8->setMaximumSize( 32767, 32767 );
	qtarch_Label_8->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_8->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_8->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_8->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_8->setText( "" );
	qtarch_Label_8->setAlignment( 289 );
	qtarch_Label_8->setMargin( -1 );

	QLabel* qtarch_Label_9;
	qtarch_Label_9 = new QLabel( this, "Label_9" );
	qtarch_Label_9->setGeometry( 225, 153, 40, 37 );
	qtarch_Label_9->setMinimumSize( 0, 0 );
	qtarch_Label_9->setMaximumSize( 32767, 32767 );
	qtarch_Label_9->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_9->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_9->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_9->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_9->setText( "" );
	qtarch_Label_9->setAlignment( 289 );
	qtarch_Label_9->setMargin( -1 );

	QLabel* qtarch_Label_10;
	qtarch_Label_10 = new QLabel( this, "Label_10" );
	qtarch_Label_10->setGeometry( 225, 5, 40, 30 );
	qtarch_Label_10->setMinimumSize( 40, 30 );
	qtarch_Label_10->setMaximumSize( 40, 30 );
	qtarch_Label_10->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_10->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_10->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_10->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_10->setText( "" );
	qtarch_Label_10->setAlignment( 289 );
	qtarch_Label_10->setMargin( -1 );

	QBoxLayout* qtarch_layout_1 = new QBoxLayout( this, QBoxLayout::TopToBottom, 5, 5, NULL );
	qtarch_layout_1->addStrut( 0 );
	QBoxLayout* qtarch_layout_1_1 = new QBoxLayout( QBoxLayout::LeftToRight, 10, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_1, 1 );
	qtarch_layout_1_1->addStrut( 0 );
	QBoxLayout* qtarch_layout_1_1_1 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_1, 1 );
	qtarch_layout_1_1_1->addStrut( 0 );
	qtarch_layout_1_1_1->addWidget( qtarch_Label_4, 0, 9 );
	qtarch_layout_1_1_1->addWidget( m_Users, 1, 36 );
	QBoxLayout* qtarch_layout_1_1_2 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_2, 0 );
	qtarch_layout_1_1_2->addStrut( 0 );
	qtarch_layout_1_1_2->addWidget( qtarch_Label_10, 0, 36 );
	qtarch_layout_1_1_2->addWidget( qtarch_Label_8, 1, 36 );
	qtarch_layout_1_1_2->addWidget( pbadd, 0, 12 );
	qtarch_layout_1_1_2->addWidget( pbdel, 0, 20 );
	qtarch_layout_1_1_2->addWidget( qtarch_Label_9, 1, 36 );
	QBoxLayout* qtarch_layout_1_1_3 = new QBoxLayout( QBoxLayout::TopToBottom, 5, NULL );
	qtarch_layout_1_1->addLayout( qtarch_layout_1_1_3, 1 );
	qtarch_layout_1_1_3->addStrut( 0 );
	qtarch_layout_1_1_3->addWidget( qtarch_Label_5, 1, 9 );
	qtarch_layout_1_1_3->addWidget( m_Group, 1, 36 );
	QBoxLayout* qtarch_layout_1_2 = new QBoxLayout( QBoxLayout::LeftToRight, 10, NULL );
	qtarch_layout_1->addLayout( qtarch_layout_1_2, 0 );
	qtarch_layout_1_2->addStrut( 0 );
	qtarch_layout_1_2->addWidget( qtarch_Label_6, 1, 36 );
	qtarch_layout_1_2->addWidget( pbok, 1, 36 );
	qtarch_layout_1_2->addWidget( pbcancel, 1, 36 );
	qtarch_layout_1_2->addWidget( qtarch_Label_7, 1, 36 );
	resize( 490,230 );
	setMinimumSize( 480, 160 );
	setMaximumSize( 32767, 32767 );
}


editGroupData::~editGroupData()
{
}
void editGroupData::ok()
{
}
void editGroupData::cancel()
{
}
void editGroupData::add()
{
}
void editGroupData::del()
{
}
