/**********************************************************************

	--- Qt Architect generated file ---

	File: open_ksircData.h
	Last generated: Sat Oct 17 21:43:56 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef open_ksircData_included
#define open_ksircData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qpushbt.h>
#include "enter_combo.h"
#include <qcombo.h>
#include <kapp.h>

class open_ksircData : public QDialog
{
    Q_OBJECT

public:

    open_ksircData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~open_ksircData();

public slots:


protected slots:


protected:
    QPushButton* PB_Connect;
    QPushButton* PB_Cancel;
    QPushButton* PB_Edit;
    QComboBox* ComboB_ServerGroup;
    QComboBox* ComboB_ServerPort;
    QLabel* Label_ServerDesc;
    EnterCombo* ComboB_ServerName;

};

#endif // open_ksircData_included
