/*
* gridbagc.h -- Declaration of class KBagConstraints.
* Generated by newclass on Mon May  4 15:58:10 EST 1998.
*/
#ifndef SSK_BAGCONST_H
#define SSK_BAGCONST_H

/**
* @short KBagConstraints
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id: bagconst.h,v 1.3 1999/01/10 18:17:01 ssk Exp $
*/
class KBagConstraints
{

public:


private:
	int _gridx;
	int _gridy;
	int _xSpan;
	int _ySpan;
	int _resizePolicy;
	int _xSpace;
	int _ySpace;
	int _align;

public:
	enum ResizePolicy {
		NoResize	= 0,
		Horizontal	= 1,
		Vertical	= 2,
		Both		= Horizontal | Vertical
	};

	enum Align {
		Left	= 1,
		Right	= 2,
		Top	= 4,
		Bottom	= 8,
		TopLeft	=	Top | Left,
		TopRight =	Top | Right,
		BottomLeft=	Bottom | Left,
		BottomRight=	Bottom| Right,
		VCenter	= 16,
		HCenter	= 32,
		Center	=	VCenter | HCenter
	};


	KBagConstraints();

	int gridX() const { return _gridx; }
	void setGridX( int t ) { _gridx = t; }

	int gridY() const { return _gridy; }
	void setGridY( int t ) { _gridy = t; }

	int xSpan() const { return _xSpan; }
	void setXSpan( int t ) { _xSpan = t; }

	int ySpan() const { return _ySpan; }
	void setYSpan( int t ) { _ySpan = t; }

	int resizePolicy() const { return _resizePolicy; }
	void setResizePolicy( int t ) { _resizePolicy = t; }

	int align() const { return _align; }
	void setAlign( int align ) { _align = align; }

	int xSpace() const { return _xSpace; }
	void setXSpace( int t ) { _xSpace = t; }

	int ySpace() const { return _ySpace; }
	void setYSpace( int t ) { _ySpace = t; }
};

#endif // SSK_BAGCONST_H
