/*
* numdlg.h -- Declaration of class KNumDialog.
* Generated by newclass on Fri Oct  9 01:51:29 EST 1998.
*/
#ifndef SSK_NUMDLG_H
#define SSK_NUMDLG_H

#include<qdialog.h>

class QLabel;
class QLineEdit;

/**
* Request a numeric value from the user.
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id: numdlg.h,v 1.2 1998/10/16 04:07:42 ssk Exp $
*/
class KNumDialog : public QDialog
{
public:
	/**
	* KNumDialog Constructor
	*/
	KNumDialog( QWidget *parent = 0 );

	/**
	* Get a number from the user.
	*/
	bool getNum( int& num, const char *message = 0 );

	/**
	* Get a number from the user.
	*/
	bool getNum( double& num, const char *message = 0 );

	/**
	* KNumDialog Destructor
	*/
	virtual ~KNumDialog();
	
private:
	KNumDialog& operator=( KNumDialog& );
	KNumDialog( const KNumDialog& );

	QLabel	*_message;
	QLineEdit *_edit;
};

#endif // SSK_NUMDLG_H
