/**********************************************************************

	--- Dlgedit generated file ---

	File: optdata.h
	Last generated: Wed Jun 4 23:08:05 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef KornOptData_included
#define KornOptData_included

#include <qdialog.h>
#include <qlined.h>
#include <qlistbox.h>
#include <qpushbt.h>

class KornOptData : public QDialog
{
    Q_OBJECT

public:

    KornOptData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~KornOptData();

public slots:


protected slots:

    virtual void dataChanged();
    virtual void boxHighlight(int);
    virtual void cancelClicked();
    virtual void boxSelect(int);
    virtual void newBox();
    virtual void okClicked();
    virtual void dataChanged(const char*);
    virtual void deleteBox();

protected:
    QListBox* boxList;
    QPushButton* okButton;
    QPushButton* cancelButton;
    QPushButton* NewBox;
    QPushButton* DeleteBox;
    QLineEdit* boxName;
    QLineEdit* boxCaption;
    QLineEdit* boxPath;
    QLineEdit* pollTime;
    QLineEdit* notifyCmd;
    QLineEdit* clickCmd;

};

#endif // KornOptData_included
