/**********************************************************************

	--- Dlgedit generated file ---

	File: CDDialogData.cpp
	Last generated: Thu Jan 1 15:56:19 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "CDDialogData.h"

#define Inherited QDialog

#include <qframe.h>
#include <qlabel.h>
#include <klocale.h>
#include <kapp.h>

CDDialogData::CDDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name )
{
	titleedit = new QLineEdit( this, "titleedit" );
	titleedit->setGeometry( 20, 35, 320, 28 );
	titleedit->setText( "" );
	titleedit->setMaxLength( 70 );
	titleedit->setEchoMode( QLineEdit::Normal );
	titleedit->setFrame( TRUE );

	listbox = new QListBox( this, "listbox" );
	listbox->setGeometry( 20, 110, 320, 170 );
	connect( listbox, SIGNAL(highlighted(int)), SLOT(titleselected(int)) );
	listbox->setFrameStyle( 51 );
	listbox->setLineWidth( 2 );

	QFrame* tmpQFrame;
	tmpQFrame = new QFrame( this, "Frame_1" );
	tmpQFrame->setGeometry( 15, 65, 430, 15 );
	tmpQFrame->setFrameStyle( 52 );

	trackedit = new QLineEdit( this, "trackedit" );
	trackedit->setGeometry( 20, 315, 320, 30 );
	trackedit->setText( "" );
	trackedit->setMaxLength( 70 );
	trackedit->setEchoMode( QLineEdit::Normal );
	trackedit->setFrame( TRUE );

	progseq_edit = new QLineEdit( this, "programsequence_edit" );
	progseq_edit->setGeometry( 20, 375, 320, 30 );
	progseq_edit->setText( "" );
	progseq_edit->setMaxLength( 70 );
	progseq_edit->setEchoMode( QLineEdit::Normal );
	progseq_edit->setFrame( TRUE );

	tmpQFrame = new QFrame( this, "hline2" );
	tmpQFrame->setGeometry( 15, 410, 430, 10 );
	tmpQFrame->setFrameStyle( 52 );

	save_button = new QPushButton( this, "save_button" );
	save_button->setGeometry( 15, 425, 85, 25 );
	save_button->setText( klocale->translate("Save") );
	save_button->setAutoRepeat( FALSE );
	save_button->setAutoResize( FALSE );

	load_button = new QPushButton( this, "PushButton_3" );
	load_button->setGeometry( 185, 425, 85, 25 );
	load_button->setText( klocale->translate("Load") );
	load_button->setAutoRepeat( FALSE );
	load_button->setAutoResize( FALSE );

	ok_button = new QPushButton( this, "PushButton_4" );
	ok_button->setGeometry( 355, 425, 85, 25 );
	ok_button->setText( klocale->translate("Close") );
	ok_button->setAutoRepeat( FALSE );
	ok_button->setAutoResize( FALSE );

	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_2" );
	tmpQLabel->setGeometry( 105, 355, 185, 20 );
	tmpQLabel->setText( klocale->translate("Play List Editor") );
	tmpQLabel->setAlignment( 292 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_3" );
	tmpQLabel->setGeometry( 100, 295, 185, 20 );
	tmpQLabel->setText( klocale->translate("Edit Track Title") );
	tmpQLabel->setAlignment( 292 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_4" );
	tmpQLabel->setGeometry( 100, 15, 185, 20 );
	tmpQLabel->setText( klocale->translate("Disc Artist / Title") );
	tmpQLabel->setAlignment( 292 );
	tmpQLabel->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_5" );
	tmpQLabel->setGeometry( 100, 90, 185, 20 );
	tmpQLabel->setText( klocale->translate("Track / Time / Title") );
	tmpQLabel->setAlignment( 292 );
	tmpQLabel->setMargin( -1 );

	ext_info_title_button = new QPushButton( this, "PushButton_5" );
	ext_info_title_button->setGeometry( 360, 35, 85, 25 );
	ext_info_title_button->setText( klocale->translate("Ext Info") );
	ext_info_title_button->setAutoRepeat( FALSE );
	ext_info_title_button->setAutoResize( FALSE );

	ext_info_button = new QPushButton( this, "extinfo_button" );
	ext_info_button->setGeometry( 360, 110, 85, 25 );
	ext_info_button->setText( klocale->translate("Ext Info") );
	ext_info_button->setAutoRepeat( FALSE );
	ext_info_button->setAutoResize( FALSE );

	tmpQFrame = new QFrame( this, "Frame_3" );
	tmpQFrame->setGeometry( 360, 180, 85, 55 );
	tmpQFrame->setFrameStyle( 49 );

	disc_id_label = new QLabel( this, "diskid_label" );
	disc_id_label->setGeometry( 365, 185, 75, 45 );
	disc_id_label->setText( "" );
	disc_id_label->setAlignment( 292 );
	disc_id_label->setMargin( -1 );

	tmpQLabel = new QLabel( this, "Label_7" );
	tmpQLabel->setGeometry( 355, 155, 90, 20 );
	tmpQLabel->setText( klocale->translate("Disc ID") );
	tmpQLabel->setAlignment( 292 );
	tmpQLabel->setMargin( -1 );

	total_time_label = new QLabel( this, "totaltimelabel" );
	total_time_label->setGeometry( 360, 315, 85, 40 );
	total_time_label->setText( "" );
	total_time_label->setAlignment( 292 );
	total_time_label->setMargin( -1 );

	upload_button = new QPushButton( this, "PushButton_8" );
	upload_button->setGeometry( 360, 255, 85, 25 );
	upload_button->setText( klocale->translate("Upload") );
	upload_button->setAutoRepeat( FALSE );
	upload_button->setAutoResize( FALSE );

	resize( 465, 460 );
}


CDDialogData::~CDDialogData()
{
}
void CDDialogData::titleselected(int)
{
}
