/**********************************************************************

	--- Qt Architect generated file ---

	File: FirstStartData.h
	Last generated: Sat Feb 7 11:11:14 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef FirstStartData_included
#define FirstStartData_included

#include <qdialog.h>
#include <qpushbt.h>
#include <qradiobt.h>

class FirstStartData : public QDialog
{
    Q_OBJECT

public:

    FirstStartData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~FirstStartData();

public slots:


protected slots:


protected:
    QPushButton* b_ok;
    QRadioButton* rb_bsd;
    QRadioButton* rb_ppr;
    QRadioButton* rb_lprng;

};

#endif // FirstStartData_included
