/**********************************************************************

	--- Qt Architect generated file ---

	File: ksprogressdata.h
	Last generated: Thu Dec 18 09:09:53 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ksprogressData_included
#define ksprogressData_included

#include <qframe.h>
#include <qlabel.h>
#include "kprogress.h"

class ksprogressData : public QFrame
{
    Q_OBJECT

public:

    ksprogressData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~ksprogressData();

public slots:


protected slots:

    virtual void cancelPressed();

protected:
    KProgress* progress;
    QLabel* fileName;
    QLabel* transferStatus;

};

#endif // ksprogressData_included
