#!/usr/bin/perl

my $file;

foreach $file (@ARGV){
    open(FILE, $file) || warn "Can't open $file: $!\n", next;
    my @file = <FILE>;
    close FILE;
    if( ! grep(/kapp\.h/, @file)){
        my $i = 0;
        for(; $i <= $#file; $i++){
            if($file[$i] =~ /^class /){
                splice(@file, $i-1, 0, "#include <kapp.h>\n");
                $i++;
            }
        }
        open(WFILE, ">$file")  || warn "Can't write $file: $!\n", next;;
        print WFILE @file;
        close WFILE;
    }
}