/**********************************************************************

	--- Qt Architect generated file ---

	File: dccDialogData.h
	Last generated: Wed Dec 17 21:36:10 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef dccDialogData_included
#define dccDialogData_included

#include <qframe.h>
#include <qpushbt.h>
#include <qlistbox.h>
#include <kapp.h>

class dccDialogData : public QFrame
{
    Q_OBJECT

public:

    dccDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~dccDialogData();

public slots:


protected slots:


protected:
    QListBox* fileList;
    QPushButton* getButton;
    QPushButton* forgetButton;

};

#endif // dccDialogData_included
