/**********************************************************************

	--- Qt Architect generated file ---

	File: dccDialogData.cpp
	Last generated: Wed Dec 17 21:36:10 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "dccDialogData.h"

#define Inherited QFrame


dccDialogData::dccDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	fileList = new("QListBox") QListBox( this, "ListBox_1" );
	fileList->setGeometry( 10, 10, 210, 190 );
	fileList->setMinimumSize( 10, 10 );
	fileList->setMaximumSize( 32767, 32767 );
	fileList->setFrameStyle( 51 );
	fileList->setLineWidth( 2 );
	fileList->setMultiSelection( FALSE );

	getButton = new("QPushButton") QPushButton( this, "PushButton_1" );
	getButton->setGeometry( 10, 210, 100, 30 );
	getButton->setMinimumSize( 10, 10 );
	getButton->setMaximumSize( 32767, 32767 );
	getButton->setText( i18n("&Get") );
	getButton->setAutoRepeat( FALSE );
	getButton->setAutoResize( FALSE );

	forgetButton = new("QPushButton") QPushButton( this, "PushButton_2" );
	forgetButton->setGeometry( 120, 210, 100, 30 );
	forgetButton->setMinimumSize( 10, 10 );
	forgetButton->setMaximumSize( 32767, 32767 );
	forgetButton->setText( i18n("&Forget") );
	forgetButton->setAutoRepeat( FALSE );
	forgetButton->setAutoResize( FALSE );

	resize( 230,250 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


dccDialogData::~dccDialogData()
{
}
#include "dccDialogData.moc"
