/**********************************************************************

	--- Qt Architect generated file ---

	File: KSircColourData.cpp
	Last generated: Fri Jul 24 19:46:48 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "KSircColourData.h"

#define Inherited QFrame

#include <qlabel.h>
#include <qpushbt.h>

KSircColourData::KSircColourData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 12288 )
{
	QLabel* dlgedit_Label_1;
	dlgedit_Label_1 = new("QLabel") QLabel( this, "Label_1" );
	dlgedit_Label_1->setGeometry( 10, 10, 100, 30 );
	dlgedit_Label_1->setMinimumSize( 10, 10 );
	dlgedit_Label_1->setMaximumSize( 32767, 32767 );
	dlgedit_Label_1->setText( i18n("Generic Text") );
	dlgedit_Label_1->setAlignment( 289 );
	dlgedit_Label_1->setMargin( -1 );

	ColourText = new("KColorButton") KColorButton( this, "User_1" );
	ColourText->setGeometry( 120, 10, 100, 30 );
	ColourText->setMinimumSize( 10, 10 );
	ColourText->setMaximumSize( 32767, 32767 );

	ColourInfo = new("KColorButton") KColorButton( this, "User_2" );
	ColourInfo->setGeometry( 120, 50, 100, 30 );
	ColourInfo->setMinimumSize( 10, 10 );
	ColourInfo->setMaximumSize( 32767, 32767 );

	ColourChan = new("KColorButton") KColorButton( this, "User_3" );
	ColourChan->setGeometry( 120, 90, 100, 30 );
	ColourChan->setMinimumSize( 10, 10 );
	ColourChan->setMaximumSize( 32767, 32767 );

	ColourError = new("KColorButton") KColorButton( this, "User_4" );
	ColourError->setGeometry( 120, 130, 100, 30 );
	ColourError->setMinimumSize( 10, 10 );
	ColourError->setMaximumSize( 32767, 32767 );

	QLabel* dlgedit_Label_2;
	dlgedit_Label_2 = new("QLabel") QLabel( this, "Label_2" );
	dlgedit_Label_2->setGeometry( 10, 50, 100, 30 );
	dlgedit_Label_2->setMinimumSize( 10, 10 );
	dlgedit_Label_2->setMaximumSize( 32767, 32767 );
	dlgedit_Label_2->setText( i18n("Info") );
	dlgedit_Label_2->setAlignment( 289 );
	dlgedit_Label_2->setMargin( -1 );

	QLabel* dlgedit_Label_3;
	dlgedit_Label_3 = new("QLabel") QLabel( this, "Label_3" );
	dlgedit_Label_3->setGeometry( 10, 90, 100, 30 );
	dlgedit_Label_3->setMinimumSize( 10, 10 );
	dlgedit_Label_3->setMaximumSize( 32767, 32767 );
	dlgedit_Label_3->setText( i18n("Chan Messages") );
	dlgedit_Label_3->setAlignment( 289 );
	dlgedit_Label_3->setMargin( -1 );

	QLabel* dlgedit_Label_4;
	dlgedit_Label_4 = new("QLabel") QLabel( this, "Label_4" );
	dlgedit_Label_4->setGeometry( 10, 130, 100, 30 );
	dlgedit_Label_4->setMinimumSize( 10, 10 );
	dlgedit_Label_4->setMaximumSize( 32767, 32767 );
	dlgedit_Label_4->setText( i18n("Errors") );
	dlgedit_Label_4->setAlignment( 289 );
	dlgedit_Label_4->setMargin( -1 );

	QPushButton* dlgedit_PushButton_1;
	dlgedit_PushButton_1 = new("QPushButton") QPushButton( this, "PushButton_1" );
	dlgedit_PushButton_1->setGeometry( 120, 210, 100, 30 );
	dlgedit_PushButton_1->setMinimumSize( 10, 10 );
	dlgedit_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_1, SIGNAL(clicked()), SLOT(ok()) );
	dlgedit_PushButton_1->setText( i18n("OK") );
	dlgedit_PushButton_1->setAutoRepeat( FALSE );
	dlgedit_PushButton_1->setAutoResize( FALSE );
	dlgedit_PushButton_1->setAutoDefault( TRUE );

	QPushButton* dlgedit_PushButton_2;
	dlgedit_PushButton_2 = new("QPushButton") QPushButton( this, "PushButton_2" );
	dlgedit_PushButton_2->setGeometry( 10, 210, 100, 30 );
	dlgedit_PushButton_2->setMinimumSize( 10, 10 );
	dlgedit_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( dlgedit_PushButton_2, SIGNAL(clicked()), SLOT(cancel()) );
	dlgedit_PushButton_2->setText( i18n("Cancel") );
	dlgedit_PushButton_2->setAutoRepeat( FALSE );
	dlgedit_PushButton_2->setAutoResize( FALSE );

	ColourBackground = new("KColorButton") KColorButton( this, "User_5" );
	ColourBackground->setGeometry( 120, 170, 100, 30 );
	ColourBackground->setMinimumSize( 10, 10 );
	ColourBackground->setMaximumSize( 32767, 32767 );

	QLabel* dlgedit_Label_5;
	dlgedit_Label_5 = new("QLabel") QLabel( this, "Label_5" );
	dlgedit_Label_5->setGeometry( 10, 170, 100, 30 );
	dlgedit_Label_5->setMinimumSize( 10, 10 );
	dlgedit_Label_5->setMaximumSize( 32767, 32767 );
	dlgedit_Label_5->setText( i18n("Background") );
	dlgedit_Label_5->setAlignment( 289 );
	dlgedit_Label_5->setMargin( -1 );

	resize( 230,250 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


KSircColourData::~KSircColourData()
{
}
void KSircColourData::ok()
{
}
void KSircColourData::cancel()
{
}
#include "KSircColourData.moc"
