/**********************************************************************

	--- Qt Architect generated file ---

	File: open_topData.h
	Last generated: Thu Dec 4 21:25:20 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef open_topData_included
#define open_topData_included

#include <qdialog.h>
#include <qpushbt.h>
#include <qcombo.h>
#include <kapp.h>

class open_topData : public QDialog
{
    Q_OBJECT

public:

    open_topData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~open_topData();

public slots:


protected slots:

    virtual void terminate();
    virtual void create_toplevel();

protected:
    QPushButton* okButton;
    QComboBox* nameSLE;

};

#endif // open_topData_included
