/**********************************************************************

	--- Qt Architect generated file ---

	File: welcomeWinData.h
	Last generated: Sun Oct 25 00:01:05 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef welcomeWinData_included
#define welcomeWinData_included

#include <qdialog.h>
#include <qchkbox.h>
#include <qpushbt.h>
#include "irclistbox.h"
#include <kapp.h>

class welcomeWinData : public QDialog
{
    Q_OBJECT

public:

    welcomeWinData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~welcomeWinData();

public slots:


protected slots:

    virtual void dismiss();

protected:
    KSircListBox* DisplayDialog;
    QCheckBox* ShowAgain;
    QPushButton* But_dismiss;

};

#endif // welcomeWinData_included
