/**********************************************************************

	--- Dlgedit generated file ---

	File: MiscData.h
	Last generated: Tue Jun 24 22:20:11 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef MiscData_included
#define MiscData_included

#include <qdialog.h>
#include <qcombo.h>
#include <qpushbt.h>
#include <qradiobt.h>

#include "about.h"

#include "Data.h"

class MiscData : public QDialog
{
    Q_OBJECT

public:

    MiscData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~MiscData();

    Data *data;

public slots:


protected slots:

    virtual void ResetButtonClicked();
    virtual void InitializeClicked();
    virtual void HelpClicked();
    virtual void AboutClicked();
    virtual void PageProtectSelected(const char*);
    virtual void DosButtonClicked();
    virtual void EjectButtonClicked();
    virtual void PowerSaveComboSelected(const char*);
    virtual void UnixButtonClicked();

protected:
    QButtonGroup* ReturnButtonGroup;
    QRadioButton* UnixButton;
    QRadioButton* DosButton;
    QComboBox* PageProtectCombo;
    QComboBox* PowerSaveCombo;
    QPushButton* EjectButton;
    QPushButton* ResetButton;
    QPushButton* Initialize;
    QPushButton* Help;
    QPushButton* About;

};

#endif // MiscData_included
